[package]
name = "veritas"
version = "0.1.0"
authors = ["Tanishq Dubey <tanishq.dubey@gmail.com>"]

[dependencies]
git2 = "0.6.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.31"
colored = "1.6"
